Repository DRV2VNA/Flats.io, pull requests merged in 2021-02, with the labels that each got.

#8 Feature 2 main entities
  pom.xml
  src/main/java/io/flats/controller/restfull.java
  src/main/java/io/flats/entity/BaseEntity.java
  src/main/java/io/flats/entity/Flat.java
  src/main/java/io/flats/entity/Role.java
  src/main/java/io/flats/entity/User.java
  src/main/resources/application.properties
  src/main/resources/dev-postgres.sql
Labels: Add new, backend: develop, wontfix

#13 CodeCov доработан.
  pom.xml
Labels: Add new, deployment: fix, documentation

#16 Добавлен Frontend на React
  react-app/.gitignore
  react-app/README.md
  react-app/package-lock.json
  react-app/package.json
  react-app/public/favicon.ico
  react-app/public/index.html
  react-app/public/logo192.png
  react-app/public/logo512.png
  react-app/public/manifest.json
  react-app/public/robots.txt
  react-app/src/App.css
  react-app/src/App.js
  react-app/src/App.test.js
  react-app/src/ErrorPage.js
  react-app/src/index.css
  react-app/src/index.js
  react-app/src/logo.svg
  react-app/src/reportWebVitals.js
  react-app/src/setupTests.js
  src/main/java/io/flats/entity/Flat.java
Labels: Add new, frontend: develop

#24 Добавлены базовые контроллеры
  src/main/java/io/flats/controller/ServiceController.java
  src/main/java/io/flats/dto/BasicResponce.java
  src/main/java/io/flats/dto/FlatDto.java
  src/main/java/io/flats/dto/ResponceCompletedDto.java
  src/main/java/io/flats/dto/ResponceNotCompletedDto.java
  src/main/java/io/flats/entity/Flat.java
  src/main/java/io/flats/entity/FlatOrderType.java
  src/main/java/io/flats/exception/ApiClientException.java
  src/main/java/io/flats/exception/ApiException.java
  src/main/java/io/flats/exception/ApiServerException.java
  src/main/java/io/flats/exception/UserNotFoundExeption.java
  src/main/java/io/flats/payload/FilterDtoPayload.java
  src/main/java/io/flats/payload/FlatDtoPayload.java
  src/main/java/io/flats/repository/FlatOrderTypeRepository.java
  src/main/java/io/flats/repository/FlatRepository.java
  src/main/java/io/flats/repository/UserRepository.java
  src/main/java/io/flats/service/FlatService.java
  src/main/resources/dev-postgres.sql
Labels: backend: develop

#26 Feature 25 add controller ping
  src/main/java/io/flats/controller/restfull.java
  src/main/java/io/flats/dto/BasicResponce.java
  src/main/java/io/flats/dto/ResponceCompletedDto.java
Labels: Add new, backend: develop
